export PATH := "./node_modules/.bin:" + env_var('PATH')

help:
    @just --list --unsorted

run:
    vite
alias r := run

clean:
    rm -rf build

bootstrap:
    pnpm install


release:
    mkdir -p build/
    cp index.html build/index.html
    cp -r build-cache/* build/
    ls -R build

run-release:
    cd build && python3 -m http.server

deploy:
    render deploy tsdoc.static
